FoodApp/urls.py
from django.urls import path
from FoodApp import views
app_name= 'FoodApp'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:item_id>/',views.detail,name='detail'),
    path('add/',views.create_item,name='create_item'),
    path('update/<int:id>/',views.update_item,name='update'),
    path('delete/<int:id>/',views.delete_item,name='delete'),
]

Practice/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('FoodApp.urls')),
    path('users/',include('users.urls')),
    path('login/',views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
]

urlpatterns += []+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name='users'
urlpatterns=[
    path('register/',views.register,name='register'),
    path('profile/',views.profile,name='profile'),
]

FoodApp/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    def __str__(self):
        return self.item_name
    item_name=models.CharField(max_length=122)
    item_desc=models.CharField(max_length=122)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=5000,default='https://t3.ftcdn.net/jpg/04/17/41/92/360_F_417419275_y8vQY8TXGRpQGpsgkkqihUaWpmtukRhY.jpg')
 

users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user_instance=models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='Profile_image/',default="profile.jpg")
    full_name=models.CharField(max_length=30,blank=True)
    bio=models.TextField(blank=True)
    location=models.CharField(max_length=50,blank=True)
    date_of_birth=models.DateField(null=True,blank=True)
    email=models.EmailField(blank=True)
    phone=models.CharField(max_length=12,blank=True)
    website=models.URLField(blank=True)

FoodApp/forms.py
from django import forms
from FoodApp.models import Item
class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

FoodApp/views.py
# from django.http import HttpResponse
# from django.http import HttpResponse
from django.shortcuts import render
from FoodApp.models import Item
from FoodApp.forms import ItemForm
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def index(request):
    item_list=Item.objects.all()
    context={
        'item_list':item_list,
    }
    return render(request,'FoodApp/index.html',context)
def detail(request,item_id):
    item=Item.objects.get(pk=item_id)
    context={
        'item':item,
    } 
    return render(request,'FoodApp/details.html',context)

def create_item(request):
    form=ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('FoodApp:index') 
    return render(request,'FoodApp/item_form.html',{'forms':form})
def update_item(request,id):
    item=Item.objects.get(id=id)
    form=ItemForm(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('FoodApp:index')
    return render(request,'FoodApp/item_form.html',{'forms':form})
def delete_item(request,id):
    item=Item.objects.get(id=id)
    if request.method=='POST':
        item.delete()
        return redirect('FoodApp:index')
    return render(request,'FoodApp/delete_msg.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from users.models import Profile

# Create your views here.
def register(request):
    form=UserCreationForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('login')
    return render(request,'users/register.html',{'form':form})

def profile(request):
    profile_instance=Profile.objects.get(user_instance=request.user)
    return render(request,'users/profile.html',{'profile_instance':profile_instance})

FoodApp/templates/FoodApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base Doc</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'FoodApp/style.css' %}">
</head>

<body>
    {% csrf_token %}
    <nav class="navbar navbar-inverse">

        <div class="container-fluid">

            <div class="navbar-header">

                <a class="navbar-brand" href="{% url 'FoodApp:index' %}" style='font-weight:bold'>FoodApp</a>

            </div>

            <ul class="nav navbar-nav">

                <li><a href="{% url 'users:profile' %}">Profile</a></li>

                <li>
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link" style="color: #adabab;">Logout</button>
                    </form>
                </li>

            </ul>

        </div>

    </nav>
    {% block body %}
    {% endblock %}

</body>

</html>

FoodApp/templates/FoodApp/delete_msg.html
<form method="POST">
    {% csrf_token %}
<h1>Are you sure to delete {{item.item_name}}</h1>
<button type="submit">confirm</button>
</form>

FoodApp/templates/FoodApp/details.html
{% extends "FoodApp/base.html" %}
{% block body %}
<div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-5">
        <img src="{{ item.item_image }}" alt="loading" height="300px" class="card">
    </div>
    <div class="col-md-4">
        <h3 style="font-family: cursive;font-weight: bold;">{{ item.item_name }}</h3>
        <h4 style="font-family: cursive;font-weight: bold;">{{ item.item_desc }}</h4>
        <h5 style="font-family: cursive;font-weight: bold;">{{ item.item_price }}</h5>
    </div>
    <div class="col-md-2">
        <a href="{% url 'FoodApp:update' item.id %}" class="btn btn-success" style="background-color: black;">Update</a>
        <br><br>
        <a href="{% url 'FoodApp:delete' item.id %}" class="btn btn-success" style="background-color: black;">Delete</a>
        <br><br>
        
        <a href="{% url 'FoodApp:create_item' %}" class="btn btn-success" style="background-color: black;">Add Item</a>
    </div>
</div>
{% endblock %}

FoodApp/templates/FoodApp/index.html
{% extends "FoodApp/base.html" %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Item List</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
</head>

<body>
{% csrf_token %}
    <div class="container">
        {% block body %}
        {% for item in item_list %}
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-4">
                <img src="{{ item.item_image }}" height="200px" class="card">
            </div>
            <div class="col-md-3">
                <h3 style="font-family: cursive; font-weight: bold;">{{ item.item_name }}</h3>
            </div>
            <div class="col-md-3">
                <a href="{% url 'FoodApp:detail' item.id %}" class="btn btn-success" style="background-color: black;">
                    Click here<br>
                </a>
            </div>
        </div>
        <br>
        <hr><br>
        {% endfor %}
        {% endblock %}
    </div>
</body>

</html>

FoodApp/templates/FoodApp/item_form.html
<style>
    
    body {
        font-family: Arial, sans-serif;
    }
    form {
        width: 300px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #f1f1f1;
        background: #c5bcbc;
        box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.1);
    }
    form input, form button {   
        width: 100%;
        padding: 10px;
        margin-top: 10px;
        box-sizing: border-box;
    }
    form button {
        background: #007BFF;
        border: 0;
        color: white;
        cursor: pointer;
    }
    form button:hover {
        background: #0056b3;
    }
</style>
{% extends "FoodApp/base.html" %}
{% block body %}
<form method="post">
    {% csrf_token %}
    {{forms}}
    <button type="submit">Save</button>
</form>
{% endblock %}

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        .form-container {
            max-width: 400px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }
        .form-group {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin-bottom: 5px;
        }
 input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }
        button[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <form method='POST'>
            {% csrf_token %}
            {% for field in form %}
            <div class='form-group'>
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
            </div>
            {% endfor %}
            <input type="hidden" name='next' value="{% url 'FoodApp:index' %}">
            <button type='submit'>Login</button>
        </form>
    </div>
</body>
</html>

users/templates/users/logout.html
{% load static %}
<html>
<head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    .message-container {
        max-width: 400px;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        text-align: center;
    }
</style>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            
          </div>
          <ul class="nav navbar-nav">
            
            <li><a href="{% url 'login' %}">Login</a></li>
          </ul>
        </div>
      </nav>
      <div class="message-container">
        <h3>You've been Successfully Logged Out. </h3>
            <h4>See You Next Time!</h4>
    </div>
      {% block body %}
      {% endblock %}
</body>
</html>

users/templates/users/profile.html
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  {% extends "FoodApp/base.html" %}
  {% block body %}
  <style>
    .profile-container {
      padding: 50px;
      background-color: #f9f9f9;
      border-radius: 10px;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
      max-width: 600px;
      margin: 0 auto;
    }
    .profile-image {
      display: block;
      margin: 0 auto 20px;
      border-radius: 50%;
      box-shadow: 0 0 20px rgba(0, 0, 0, 0.3);
      transition: transform 0.3s ease-in-out;
    }
    .profile-image:hover {
      transform: scale(1.05);
    }
    .profile-username {
      margin-top: 20px;
      font-size: 28px;
      color: #333;
    }
    .edit-profile-btn {
      background-color: #4CAF50;
      color: white;
      padding: 10px 20px;
      font-size: 16px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      transition: background-color 0.3s ease-in-out;
      display: flex;
      justify-content: center;
    }
    .edit-profile-btn:hover {
      background-color: #45a049;
    }

    .profile{
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="profile-container">
    <img src="{{ user.profile.image.url }}" class="profile-image" height="250px" width="250px" style="border:5px solid #fff">
    <h1 class="profile">{{ user.username }}</h1>
  
    <h1 class="profile-username">Full Name: {{ profile_instance.full_name }}</h1>
    <p class="profile-username">Bio: {{ profile_instance.bio }}</p>
    <p class="profile-username">Location: {{ profile_instance.location }}</p>
    <p class="profile-username">Date of Birth: {{ profile_instance.date_of_birth }}</p>
    <p class="profile-username">Email: {{ profile_instance.email }}</p>
    <p class="profile-username">Phone: {{ profile_instance.phone }}</p>
    <p class="profile-username">Website: <a href="{{ profile.website }}">{{ profile_instance.website }}</a></p>
  
    <button class="edit-profile-btn" >Edit Profile</button>
  </div>
  {% endblock %}
</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>
    <style>
        /* styles.css */

/* Basic styling for the form container */
.registration-form {
    max-width: 400px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ddd;
    border-radius: 5px;
    background-color: #f9f9f9;
}

/* Style the form fields */
.registration-form input[type="text"],
.registration-form input[type="password"] {
    width: 100%;
    padding: 10px;
    margin-bottom: 15px;
    border: 1px solid #ccc;
    border-radius: 3px;
}

/* Style the submit button */
.registration-form button[type="submit"] {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 10px 20px;
    border-radius: 3px;
    cursor: pointer;
}

/* Add hover effect to the submit button */
.registration-form button[type="submit"]:hover {
    background-color: #0056b3;
}

/* Center the form vertically */
body {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
    background-color: #f5f5f5;
}

    </style>
</head>
<body>
    <div class="registration-form">
        <h2>User Register</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Register</button>
        </form>
    </div>
</body>
</html>